/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as SellRouteImport } from './routes/sell'
import { Route as StockRouteImport } from './routes/stock'
import { Route as TallyRouteImport } from './routes/tally'
import { Route as StockItemIdRouteImport } from './routes/stock.$itemId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const TallyRoute = TallyRouteImport.update({
  id: '/tally',
  path: '/tally',
  getParentRoute: () => rootRouteImport,
} as any)
const StockItemIdRoute = StockItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => StockRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/receive': typeof ReceiveRoute
  '/sell': typeof SellRoute
  '/stock': typeof StockRouteWithChildren
  '/tally': typeof TallyRoute
  '/stock/$itemId': typeof StockItemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/receive': typeof ReceiveRoute
  '/sell': typeof SellRoute
  '/stock': typeof StockRouteWithChildren
  '/tally': typeof TallyRoute
  '/stock/$itemId': typeof StockItemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/receive': typeof ReceiveRoute
  '/sell': typeof SellRoute
  '/stock': typeof StockRouteWithChildren
  '/tally': typeof TallyRoute
  '/stock/$itemId': typeof StockItemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ledger'
    | '/login'
    | '/receive'
    | '/sell'
    | '/stock'
    | '/tally'
    | '/stock/$itemId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ledger'
    | '/login'
    | '/receive'
    | '/sell'
    | '/stock'
    | '/tally'
    | '/stock/$itemId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ledger'
    | '/login'
    | '/receive'
    | '/sell'
    | '/stock'
    | '/tally'
    | '/stock/$itemId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  ReceiveRoute: typeof ReceiveRoute
  SellRoute: typeof SellRoute
  StockRoute: typeof StockRouteWithChildren
  TallyRoute: typeof TallyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tally': {
      id: '/tally'
      path: '/tally'
      fullPath: '/tally'
      preLoaderRoute: typeof TallyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$itemId': {
      id: '/stock/$itemId'
      path: '/$itemId'
      fullPath: '/stock/$itemId'
      preLoaderRoute: typeof StockItemIdRouteImport
      parentRoute: typeof StockRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StockRouteChildren {
  StockItemIdRoute: typeof StockItemIdRoute
}

const StockRouteChildren: StockRouteChildren = {
  StockItemIdRoute: StockItemIdRoute,
}

const StockRouteWithChildren = StockRoute._addFileChildren(StockRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  ReceiveRoute: ReceiveRoute,
  SellRoute: SellRoute,
  StockRoute: StockRouteWithChildren,
  TallyRoute: TallyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
